controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    position_controller:
      type: position_controllers/JointGroupPositionController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      # - MR-Buggy3/FrontRightWheelJoint # 右前轮
      # - MR-Buggy3/FrontLeftWheelJoint #左前轮
      - MR-Buggy3/RearRightWheelJoint # 右后轮
      - MR-Buggy3/RearLeftWheelJoint # 左后轮
position_controller:
  ros__parameters:
    joints:
      - MR-Buggy3/FrontRightWheelSteeringJoint # 右前转向
      - MR-Buggy3/FrontLeftWheelSteeringJoint # 左前转向
